project:
  type: book
  output-dir: ../docs

book:
  title: "LIBER Learning Hub"
  author: "LIBER DSLib & DSDCH"
  date: "31-10-2023"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "LEARNING HUB"
      chapters:
        - llms.qmd
        - automatic-text-transcription.qmd
        - collections-as-data.qmd
    - part: "ADDITIONAL RESOURCES"
      chapters:
        - competency-frameworks.qmd
        - networks.qmd
        - reports.qmd
    - part: "ABOUT"
      chapters:
        - acknowledgements.qmd
        - contributing.qmd
        - chapter-template.qmd
        - contact.qmd
    - references.qmd
  repo-url: https://github.com/nehamoopen/liber-learning-hub
  repo-actions: [edit]
  sidebar:
    logo: images/liber-logo.jpg
    
bibliography: references.bib

format:
  html:
    theme: cosmo


